# yaml-language-server: $schema=https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json
final_space: true
version: 2
# Monokai Pro https://github.com/HenriqueMiossi/Windows-Terminal-Monokai-Pro/blob/master/scheme.json
palette:
  black: "#2d2a2e"
  blue: "#6699df"
  cyan: "#78dce8"
  green: "#a9dc76"
  purple: "#ab9df2"
  red: "#ff6188"
  white: "#fcfcfa"
  yellow: "#ffd866"
  gray: "#676568"
blocks:
  - type: prompt
    alignment: left
    segments:
      - type: docker
        style: plain
        background: "#0B59E7"
        template: "/ue650 {{ .Context }} "
      - type: os
        style: plain
        foreground: p:cyan
        template: "{{ if .WSL }}\ue62a {{ end }}{{.Icon}}  "
      - type: session
        style: plain
        foreground: p:yellow
        template: "{{ if .SSHSession }}\ueba9 {{ end }}@{{ .UserName }} "
      - type: path
        style: plain
        foreground: p:white
        template: "{{ .Path }} "
        properties:
          style: letter
          home_icon: "~"
          folder_separator_icon: "/"
      - type: git
        style: plain
        foreground: p:green
        foreground_templates:
          - "{{ if or (.Working.Changed) (.Staging.Changed) }}p:yellow{{ end }}"
          - "{{ if and (gt .Ahead 0) (gt .Behind 0) }}p:red{{ end }}"
          - "{{ if gt .Ahead 0 }}p:cyan{{ end }}"
          - "{{ if gt .Behind 0 }}p:purple{{ end }}"
        template: "{{ .UpstreamIcon }}{{ .HEAD }}{{ .BranchStatus }}{{
          if .Working.Changed }} \uf044 {{ .Working.String }}{{ end }}{{
          if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{
          if .Staging.Changed }} \uf046 {{ .Staging.String }}{{ end }}{{
          if gt .StashCount 0 }} \uf692 {{ .StashCount }}{{ end }} "
        properties:
          branch_icon: "\uf126 "
          fetch_stash_count: true
          fetch_status: true
          fetch_upstream_icon: true
      - type: node
        style: plain
        foreground: "#689f63"
        template: "\ue718 {{ if .PackageManagerIcon }}{{ .PackageManagerIcon }} {{ end }}{{ .Full }} "
      - type: go
        style: plain
        foreground: "#00acd7"
        template: "\ue627 {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} "
      - type: executiontime
        style: plain
        foreground: p:gray
        template: "\ueba2 {{ .FormattedMs }}"
        properties:
          style: roundrock
          threshold: 1000
  - type: prompt
    alignment: left
    newline: true
    segments:
      - type: time
        style: plain
        foreground: p:gray
        template: "{{ .CurrentDate | date .Format }} "
        properties:
          time_format: "15:04"
      - type: text
        style: plain
        foreground: p:green
        template: "{{
          if gt .Code 0 }}<p:red>[{{ .Code }}] </>{{ end }}{{
          if .Root }}\uf0e7{{ else }}\u276f{{ end }}"
